# configure Main site (no data)
---
- hosts: xyz
  vars:
    site: 'slazav.xyz'
    wwwdir: '/var/www/main'

  tasks:
  - name: copy apache configuration - main
    template: src=apache/main.j2
              dest=/etc/apache2/conf-available/{{ site }}.conf

  - name: copy apache configuration - ssl
    template: src=apache/ssl.conf
        dest=/etc/apache2/conf-available/ssl.conf

  - name: copy apache configuration - conf
    template: src=apache/slazav.conf
              dest=/etc/apache2/sites-enabled/{{ site }}.conf

  - name: create folders if needed
    file: name={{ item.name }} state=directory mode={{ item.mode }}
    with_items:
      - { name: '{{ wwwdir }}/html/', mode: '0755'}
      - { name: '{{ wwwdir }}/data/', mode: '0777'}
      - { name: '{{ wwwdir }}/logs/', mode: '0777'}
      - { name: '{{ wwwdir }}/cgi/', mode: '0755'}
      - { name: '{{ wwwdir }}/data/sti/'  , mode: '0755'}

  - name: restart Services
    service: name={{ item.name }} state=restarted enabled=yes
    with_items:
      - { name: 'apache2' }
