# configure Tiles site
---
- hosts: xyz
  vars:
    site:   'tiles.slazav.xyz'
    wwwdir: '/var/www/tiles'

  tasks:
  - name: copy apache configuration
    template: src=apache/tiles.slazav.xyz.j2
              dest=/etc/apache2/sites-enabled/{{ site }}.conf

  - name: create folders if needed
    file: name={{ item.name }} state=directory mode={{ item.mode }}
    with_items:
      - { name: '{{ wwwdir }}/html/', mode: '0755'}
      - { name: '{{ wwwdir }}/data/', mode: '0777'}
      - { name: '{{ wwwdir }}/logs/', mode: '0777'}
      - { name: '{{ wwwdir }}/cgi/', mode: '0755'}

  - name: restart Services
    service: name={{ item.name }} state=restarted
    with_items:
      - { name: 'apache2' }
