---
- hosts: xyz

  tasks:
  - name: Get Grafana package
    get_url:
#      url: https://s3-us-west-2.amazonaws.com/grafana-releases/release/grafana_4.6.2_amd64.deb
      url: https://dl.grafana.com/oss/release/grafana_6.5.2_amd64.deb
      dest: /tmp/grafana.deb

  - name: install Grafana
    apt: deb=/tmp/grafana.deb state=present

  - name: install simple-json plugin for Grafana
    command: grafana-cli plugins install grafana-simple-json-datasource

  - name: start Grafana service
    service: name=grafana-server state=started enabled=yes

# todo: modify config (open anon access etc)

  - name: open port 3000
    ufw:
      rule: allow
      port: '3000'
      proto: tcp
