---
- hosts: xyz

  tasks:

  - name: Install/update packages
    apt: pkg={{ item.name }} state=present
    with_items:
      - { name: 'libmicrohttpd-dev' }
      - { name: 'libjansson-dev' }
      - { name: 'libdb-dev' }

  - name: Download latest graphene
    git: repo=https://github.com/slazav/graphene dest=/tmp/graphene version=HEAD

  - name: Build graphene
    make:
      chdir: /tmp/graphene/graphene

  - name: Install graphene
    make:
      target: install
      chdir: /tmp/graphene/graphene

