---
- hosts: xyz

  tasks:

  - name: Install/update packages
    apt: pkg={{ item.name }} state=present
    with_items:
      - { name: 'libmicrohttpd-dev' }
      - { name: 'libjansson-dev' }
      - { name: 'libdb-dev' }

  - name: Download latest graphene
    git: repo=https://github.com/slazav/graphene dest=/root/graphene version=HEAD

  - name: Build graphene
    make:
      chdir: /root/graphene/graphene

  - name: Install graphene
    make:
      target: install
      chdir: /root/graphene/graphene

  - name: install init script
    copy:
      remote_src: yes
      src: /root/graphene/graphene/graphene_http.init.ubuntu
      dest: /etc/init.d/graphene_http
      mode: 0755

  - name: start service
    service: name=graphene_http state=started enabled=yes

  - name: open graphene_http port
    ufw:
      rule: allow
      port: 8081
      proto: tcp
