## Configure Ubuntu system.
---
- hosts: xyz

  tasks:
  - name: Install packages
    apt: pkg={{ item.name }} state=present
    with_items:
      - { name: 'apache2' }
      - { name: 'mongodb' }
      - { name: 'libcgi-pm-perl' }
      - { name: 'libmongodb-perl' }
      - { name: 'libjson-perl' }

  - name: remove default sites
    command: sh -c 'rm -f /etc/apache2/sites-enabled/0*'

  - name: load apache modules
    file: src=/etc/apache2/mods-available/{{ item.name }}.load
          dest=/etc/apache2/mods-enabled/{{ item.name }}.load state=link
    with_items:
      - { name: 'cgi' }

  - name: restart Services
    service: name={{ item.name }} state=restarted enabled=yes
    with_items:
      - { name: 'apache2' }
      - { name: 'mongodb' }
