#!/usr/bin/perl

## HTML output for news page

################################################

use strict;
use warnings;
use Try::Tiny;
use CGI ':standard';
use JSON;
use site;
use common;
use safe_html;
use html;

################################################

try {
  ####################
  # get parameters:
  my $id   = cleanup_int(param('id')||'');
  my $num  = cleanup_int(param('num')||25);
  my $skip = cleanup_int(param('skip')||0);
  my $titles = defined param('titles');

  ####################
  # open DB, get all information:
  my $db = open_db;
  my $u  = get_my_info($db);
  my $objects;
  my $o;
  if ($id) {  $o = show_object($db, 'news', $id); }
  else { $objects = list_objects($db, 'news', $skip, $num); }

  ####################
  # Print everything:
  print_head($u);

  # print one
  if ($id) {
    my $cu = mk_face($o->{cuser_full});
    print "<div class='obj_top_panel'>$cu: <a href='news?id=$o->{_id}'>$o->{title}</a></div>\n";
    print "<p class='news_body'>$o->{text}</p>\n";
    my $src = exists $o->{origin}? " <a href='$o->{origin}'>(источник)</a>":"";
    print "<div class='obj_bottom_panel'><i>$o->{ctime_fmt}</i>$src</div>\n";
  }
  # print many
  else {

    my $n1 = $skip+1;
    my $n2 = $skip+1+$num;
    my $np = ($n1-$num-1 < 0)? 0:$n1-$num-1;
    my $nn = $n1+$num-1;
    print "<div class=navigation>\n",
      "<a href='news?skip=$np'>&lt&lt</a> $n1..$n2 <a href='news?skip=$nn'>&gt&gt</a>\n",
      "<a href='javascript:div_show(\"news_popup\");'>[новое сообщение]</a>\n",
      "</div>\n";

    foreach my $o (@{$objects}) {
      my $cu = mk_face($o->{cuser_full});
      if ($titles){
        print "<div class='title_panel'>$cu: <a href='news?id=$o->{_id}'>$o->{title}</a> <i>($o->{ctime_fmt})</i></div>\n";
      }
      else {
        print "<hr><div class='obj_top_panel'>$cu: <a href='news?id=$o->{_id}'>$o->{title}</a></div>\n";
        print "<p class='news_body'>$o->{text}</p>\n";
        my $src = exists $o->{origin}? " <a href='$o->{origin}'>(источник)</a>":"";
        print "<div class='obj_bottom_panel'><i>$o->{ctime_fmt}</i>$src</div>\n";
      }
    }
  }

  print qq*
  <!-- Всплывающий диалог нового сообщения -->
  <div style="display:none;" id="news_popup" class="fullscreen">
  <div class="fullscreen shade"></div>
  <!-- div class="i_popup" -->
  <form action="#" class="popup" id="news_form">
    <img class="close" src="img/x.png" onclick ="div_hide('news_popup')">
    <h2>Новое собщение</h2>
    <hr class="wide">
    <input  name="id" type="hidden">
    <input  name="title" placeholder="Заголовок" type="text">
    <textarea id="text" name="text" placeholder="Текст"></textarea>
    <h4>Тип новости:</h4>
    <select name="type">
      <option>1</option>
      <option>2</option>
      <option>3</option>
    </select>
    <a href="javascript:on_news_write()" class="submit_button">Опубликовать</a>
  </form>
  </div></div>
*;

  print_tail();

################################################
}
catch {
  print_error($_, 'html');
}
