#!/usr/bin/perl

## HTML output for news page

################################################

use strict;
use warnings;
use Try::Tiny;
use CGI ':standard';
use POSIX qw(strftime);
use JSON;
use site;
use common;
use safe_html;
use html;
use utf8;
use open ':std', ':encoding(UTF-8)';
use Encode;

################################################

try {
  ####################
  # get parameters:
  my $pars;
  $pars->{id}   = param('id') || '';
  $pars->{num}  = param('num') || 20;
  $pars->{skip} = param('skip') || 0;
  $pars->{titles} = defined param('titles');
  $pars->{search} = decode utf8=>(param('search') || '');

  ####################
  # open DB, get all information:
  my $db = open_db;
  my $u  = get_my_info($db);
  my $objects;
  my $o;
  my $comm;
  my $count;
  if ($pars->{id}) {
    $o = show_object($db, 'news', $pars);
    $comm = list_comments($db, {coll=>'news', id=>$pars->{id}});
  }
  else {
    ($objects, $count) = list_objects($db, 'news', $pars);
  }


  ####################
  # Print everything:
  print_head($u);

  # print one
  if ($pars->{id}) {

    my $title = cleanup_txt($o->{title});
    my $text  = cleanup_htm($o->{text});
    my $type  = cleanup_txt($o->{type});

    my $btm_panel = mk_info_panel($o, 'news');
    $btm_panel .= " <a href='javascript:show(\"news_del_popup\")'>[удалить]</a>" if $o->{can_delete};
    $btm_panel .= " <a href='javascript:on_news_undel($o->{_id})'>[восстановить]</a>" if $o->{can_undel};
    $btm_panel .= " <a href='javascript:show(\"news_popup\")'>[редактировать]</a>" if $o->{can_edit};
    $btm_panel .= " <a href='$o->{origin}'>(источник)</a>" if exists $o->{origin};

    print "<div class='title'>$title</div>\n";
    print "<div class='obj_body'>$text</p>\n";
    print "<div class='obj_info right'>$btm_panel</div>\n";
    print "<hr>\n\n";

    # comments (move to html.pm)
    print "<div class='nav center'>\n",
          "<a href='javascript:on_com_add(0)'>[новый комментарий]</a></div>\n",
          "<div id='com0'></div>\n\n";
    foreach my $c (@{$comm}){
      my $m = ($c->{depth} || 0)*20;
      my $div = "<div class='comment' style='margin-left: $m;'>\n";

      my $st = $c->{state} || '';
      if ($st eq 'D' && exists $c->{has_children}){
        print "$div<b>(deleted comment)</b>\n";
        print "</div>\n";
      }
      if ($st eq 'S' && exists $c->{has_children}){
        print "$div<b>(screened comment)</b>\n";
        print "</div>\n";
      }
      next if $st eq 'D' || $st eq 'S';

      my $cu = mk_face($c->{cuser_info});
      my $ct = strftime "%Y-%m-%d %H:%M:%S", localtime($c->{ctime});
      my $title = cleanup_txt($c->{title});
      my $text  = cleanup_htm($c->{text});
      print "$div$cu: <b>$title</b><br>\n";
      print "$text\n";
      my $btm_panel = '';
      $btm_panel .= "$ct";
      $btm_panel .= " <a href='javascript:on_com_add($c->{_id})'>[ответить]</a>";
      $btm_panel .= " <a href='javascript:on_com_edit($c->{_id})'>[редактировать]</a>" if $c->{can_edit};
      $btm_panel .= " <a href='javascript:on_com_delete($c->{_id})'>[удалить]</a>" if $c->{can_delete};
      print "<div class='com_info'>$btm_panel</div><div id='com$c->{_id}'></div>\n";
      print "</div>\n";
    }

  }
  # print many
  else {
    # protect search value
    my $search = cleanup_txt($pars->{search}); $search =~ s/\'//g;
    my $ns = $pars->{search}? "search=$pars->{search}&":"";

    # search/new panel
    my $nav_panel = '';
    $nav_panel.=" Поиск по тексту: <input type=text name=search width=15 value='$search'>";
    $nav_panel.=" <a href='javascript:show(\"news_popup\")'>[новое сообщение]</a>\n";
    print "<form action='#' class='nav right'>\n$nav_panel</form>\n";

    # << >> panel
    my $nav_panel1 = mk_count_nav "news?$ns", $pars->{skip}, $pars->{num}, $count;
    print $nav_panel1;

    foreach my $o (@{$objects}) {
      my $cu = mk_face($o->{cuser_info});
      my $ct = strftime "%Y-%m-%d %H:%M", localtime($o->{ctime});
      my $title = cleanup_txt($o->{title});
      my $text  = cleanup_htm($o->{text});
      my $type  = cleanup_txt($o->{type});
      $title = "<a href='news?id=$o->{_id}'>$title</a>";
      $text  =~ s|<lj-cut[^>]*>.*?</lj-cut>|<a href="news?id=$o->{_id}">(подробнее...)</a>|gs;

      if ($pars->{titles}){
        print "<div class='title_list'>$ct $cu: $title</div>\n";
      }
      else {
        $o->{ncomm} = $o->{ncomm} || 0;
        my $com = "<a href='news?id=$o->{_id}'>комментариев: $o->{ncomm}</a>";

        print "<hr><div class='title_list'>$cu: $title</div>\n";
        print "<p class='obj_body'>$text</p>\n";
        print "<div class='obj_info right'>$ct, $com</div>\n";
      }
    }
    print $nav_panel1;

  }

  my $id    = cleanup_int($o->{_id}   || '');
  my $title = cleanup_txt($o->{title} || '');
  my $text  = cleanup_txt($o->{text}  || '');
  my $type  = cleanup_txt($o->{type}  || '');
  print qq*
  <!-- Всплывающий диалог нового сообщения -->
  <div style="display:none;" id="news_popup" class="fullscreen">
  <div class="fullscreen shade"></div>
  <!-- div class="i_popup" -->
  <form action="javascript:on_news_write()" class="popup" id="news_form">
    <img class="close" src="img/x.png" onclick ="hide('news_popup')">
    <h2>Новое собщение</h2>
    <hr class="wide">
    <input  name="id" type="hidden" value="$id">
    <input  name="title" placeholder="Заголовок" type="text" value="$title">
    <textarea id="text" name="text" placeholder="Текст">$text</textarea>
    <h4>Тип новости:</h4>
    <select name="type">
      <option>Приглашение в поход</option>
      <option>2</option>
      <option>3</option>
    </select>
    <a href="javascript:on_news_write()" class="submit_button">Опубликовать</a>
  </form>
  </div></div>

  <!-- Всплывающий диалог предупреждения -->
  <div style="display:none;" id="news_del_popup" class="fullscreen">
  <div class="fullscreen shade"></div>
  <!-- div class="i_popup" -->
  <form action="#" class="popup" id="news_del_form">
    <img class="close" src="img/x.png" onclick ="hide('news_del_popup')">
    <h2>Удалить сообщение?</h2>
    <input name="id" type="hidden" value="$id">
    <a href="javascript:on_news_delete($id)" class="submit_button">Да</a>
  </form>
  </div></div>

*;

  print_tail();

################################################
}
catch {
  print_error($_, 'html');
}
