#!/usr/bin/perl

## HTML output for users page

################################################

use strict;
use warnings;
use Try::Tiny;
use CGI ':standard';
use POSIX qw(strftime); # date formatting
use JSON;
use site;
use common;
use safe_html;
use html;

################################################

try {
  ####################
  # get parameters:
  my $id   = cleanup_int(param('id')||'');
  my $num  = cleanup_int(param('num')||25);
  my $skip = cleanup_int(param('skip')||0);

  ####################
  # open DB, get all information:
  my $db = open_db;
  my $u  = get_my_info($db);
  my $users = user_list($db);

  # format html line for aeach user
  foreach my $uu (@{$users}) {
    my $face = "<td>" . mk_face($uu) . "</td>\n";
    my $ct = strftime "%Y-%m-%d", localtime($uu->{ctime});
    my $mt = strftime "%Y-%m-%d", localtime($uu->{mtime});
    $ct  = "<td>$ct</td>\n";
    $mt  = "<td>$mt</td>\n";

    my $lev = "<td>$level_names{$uu->{level}}</td>\n";
    if (exists $uu->{level_hints}) {
      $lev = "<td><select oninput=\"on_set_level(\'$uu->{_id}\',this.value)\">";
      foreach my $l (@{$uu->{level_hints}}) {
        my $s = ($l==$uu->{level})? " selected":"";
        $lev .= "<option value='$l'$s>$level_names{$l}</option>";
      }
      $lev.="</select></td>\n";
    }
    my $me  = exists($uu->{me})? "<td><b>-- это вы!</b></td>\n":"";
    $uu->{html} = "<tr>$face$lev$ct$mt$me</tr>\n";
  }


  ####################
  # Print everything:
  print_head($u);

  print "<table cellpadding=5><tr>\n",
        "<th>Пользователь</th>\n",
        "<th>Уровень доступа</th>\n",
        "<th>Первый вход</th>\n",
        "<th>Последний вход</th></tr>\n\n";

  foreach my $uu (@{$users}) {print $uu->{html};}
  print "</table>\n";

  print_tail();

################################################
}
catch {
  print_error($_, 'html');
}
