{
 "title": "DryDemag: fork+temperature",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "temperature, K",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "sci", "label": "temperature, K" }
   ],
   "targets": [
    { "target": "drydemag_CH6T", "type": "timeserie" },
    { "target": "drydemag_temp", "type": "timeserie" }
   ]
  },
  {
   "title": "P_cell, bar",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "drydemag_pcell", "type": "timeserie" }
   ]
  },
  {
   "title": "Fork freq",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "drydemag_fork_vz:0", "type": "timeserie" }
   ]
  },
  {
   "title": "Fork width, Hz",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "sci" }
   ],
   "targets": [
    { "target": "drydemag_fork_vz:1", "type": "timeserie" }
   ]
  }
 ]
}