{
 "title": "DryDemag",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CH1: 60K plate",
   "type": "singlestat",
   "format": "kelvin",
   "valueName": "current",
   "targets": [
    { "target": "drydemag_CH1T", "type": "timeserie" }
   ]
  },
  {
   "title": "CH2: 4K plate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "kelvin",
   "valueName": "current",
   "targets": [
    { "target": "drydemag_CH2T", "type": "timeserie" }
   ]
  },
  {
   "title": "CH5: Still",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "kelvin",
   "valueName": "current",
   "targets": [
    { "target": "drydemag_CH5T", "type": "timeserie" }
   ]
  },
  {
   "title": "CH6: Mixer",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "kelvin",
   "valueName": "current",
   "targets": [
    { "target": "drydemag_CH6T" }
   ]
  },
  {
   "title": "CH1: 60K plate (new)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "drydemag_CH1T", "type": "timeserie" }
   ]
  },
  {
   "title": "4K plate / magnet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "drydemag_CH2T", "type": "timeserie" },
    { "target": "drydemag_CH3T", "type": "timeserie" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "drydemag_CH5T", "type": "timeserie" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "drydemag_CH6T", "type": "timeserie" },
    { "target": "drydemag_temp", "type": "timeserie" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none", "label": "temperature" }
   ],
   "targets": [
    { "target": "drydemag_CH4T", "type": "timeserie" }
   ]
  },
  {
   "title": "CH7",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "drydemag_CH7R", "type": "timeserie" }
   ]
  },
  {
   "title": "CH8",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "drydemag_CH8R", "type": "timeserie" }
   ]
  },
  {
   "title": "flow",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "umol/s ?" }
   ],
   "targets": [
    { "target": "drydemag_flow", "type": "timeserie" }
   ]
  },
  {
   "title": "P1: Vacuum can",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "sci" }
   ],
   "targets": [
    { "target": "drydemag_gauge:0", "type": "timeserie" }
   ]
  },
  {
   "title": "P2: Still",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "drydemag_gauge:1", "type": "timeserie" }
   ]
  },
  {
   "title": "P3: Condensing line",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "drydemag_gauge:2", "type": "timeserie" }
   ]
  },
  {
   "title": "P4: Scroll out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "drydemag_gauge:3", "type": "timeserie" }
   ]
  },
  {
   "title": "P5: Tanks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "drydemag_gauge:4", "type": "timeserie" }
   ]
  },
  {
   "title": "P6: service line",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "drydemag_gauge:5", "type": "timeserie" }
   ]
  }
 ]
}