{
 "title": "F4 wire MCTi",
 "time": { "from": "2019-12-26T19:44:27.000Z", "to": "2019-12-26T22:54:48.464Z" },
 "panels": [
  {
   "title": "Wire sweeps",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "signal, V" }
   ],
   "targets": [
    { "target": "F4_wire_mc_cont:1", "type": "timeserie" },
    { "target": "F4_wire_mc_cont:2", "type": "timeserie" },
    { "target": "F4_wire_mc_cont:0", "type": "timeserie" }
   ]
  },
  {
   "title": "Magnet current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "current, A" }
   ],
   "targets": [
    { "target": "F4_sweep_mc_wire:0", "type": "timeserie" }
   ]
  },
  {
   "title": "Resonance width and frequency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "resonance width, Hz" }
   ],
   "targets": [
    { "target": "F4_wire_mc_fits:11", "type": "timeserie" },
    { "target": "F4_wire_mc_fits:9", "type": "timeserie" }
   ]
  },
  {
   "title": "Fit quality",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "fit error" }
   ],
   "targets": [
    { "target": "F4_wire_mc_fits:0", "type": "timeserie" },
    { "target": "F4_wire_mc_fits:12", "type": "timeserie" }
   ]
  },
  {
   "title": "Generator settings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Amplitude, V" }
   ],
   "targets": [
    { "target": "F4_wire_mc_cont_gen:0", "type": "timeserie" },
    { "target": "F4_wire_mc_cont_gen:1", "type": "timeserie" }
   ]
  },
  {
   "title": "Lockin settings",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Lockin time constant, s" }
   ],
   "targets": [
    { "target": "F4_wire_mc_cont_lockin:0", "type": "timeserie" },
    { "target": "F4_wire_mc_cont_lockin:1", "type": "timeserie" }
   ]
  }
 ]
}