{
 "title": "F4:DilutionFridge",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "F4_wire_mc_cont:1", "type": "timeserie" },
    { "target": "F4_wire_mc_cont:2", "type": "timeserie" },
    { "target": "F4_wire_mc_cont:0", "type": "timeserie" }
   ]
  },
  {
   "title": "R still",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "F4_R10", "type": "timeserie" }
   ]
  },
  {
   "title": "1K pot",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "F4_R01", "type": "timeserie" }
   ]
  },
  {
   "title": "20mK, Heat exchangers 2,4,6,8,10, Mix",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "F4_R02", "type": "timeserie" },
    { "target": "F4_R03", "type": "timeserie" },
    { "target": "F4_R04", "type": "timeserie" },
    { "target": "F4_R05", "type": "timeserie" },
    { "target": "F4_R06", "type": "timeserie" },
    { "target": "F4_R07", "type": "timeserie" },
    { "target": "F4_R08", "type": "timeserie" }
   ]
  },
  {
   "title": "Still diode, Still PT1000",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Diode voltage" }
   ],
   "targets": [
    { "target": "F4_still_diode", "type": "timeserie" },
    { "target": "F4_R09:1", "type": "timeserie" }
   ]
  },
  {
   "title": "20 mK shield (1.2k RuO) : PT1000 at 20 mK plate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "R 20mK shield, Ohm" }
   ],
   "targets": [
    { "target": "F4_R12", "type": "timeserie" },
    { "target": "F4_R11:1", "type": "timeserie" }
   ]
  },
  {
   "title": "wire magnet",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "F4_wire_magnet_r", "type": "timeserie" }
   ]
  },
  {
   "title": "R13: Mix.Ch SMB conn -- R14: Mix.Ch. magnetic conn.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "R13: Mix.ch SMB conn" }
   ],
   "targets": [
    { "target": "F4_R13", "type": "timeserie" },
    { "target": "F4_R14", "type": "timeserie" }
   ]
  },
  {
   "title": "R08: original Mix.Ch. thermometer -- R16: speer resistor at Mix.Ch.",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "R08, Ohm" }
   ],
   "targets": [
    { "target": "F4_R08", "type": "timeserie" },
    { "target": "F4_R16", "type": "timeserie" }
   ]
  },
  {
   "title": "MCTi Wire width",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short", "label": "Wire resonanse width, Hz" }
   ],
   "targets": [
    { "target": "F4_wire_mc_fits:11", "type": "timeserie" },
    { "target": "F4_wire_mc_fits:12", "type": "timeserie" }
   ]
  }
 ]
}