{
 "title": "F4:Rbath",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "He level",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "F4_he_level", "type": "timeserie" }
   ]
  },
  {
   "title": "bath diode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "F4_bath_diode", "type": "timeserie" }
   ]
  },
  {
   "title": "Bath resistors",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "F4_Rbath01", "type": "timeserie" },
    { "target": "F4_Rbath02", "type": "timeserie" },
    { "target": "F4_Rbath03", "type": "timeserie" },
    { "target": "F4_Rbath04", "type": "timeserie" },
    { "target": "F4_Rbath05", "type": "timeserie" },
    { "target": "F4_Rbath06", "type": "timeserie" },
    { "target": "F4_Rbath07", "type": "timeserie" },
    { "target": "F4_Rbath08", "type": "timeserie" },
    { "target": "F4_Rbath09", "type": "timeserie" }
   ]
  }
 ]
}