{
 "title": "Forks",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "frequency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "muki_fork1:0", "type": "timeserie" },
    { "target": "muki_fork2:0", "type": "timeserie" }
   ]
  },
  {
   "title": "1/tau (fork width), Hz",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "muki_fork1:1", "type": "timeserie" },
    { "target": "muki_fork2:1", "type": "timeserie" }
   ]
  },
  {
   "title": "Amplitude, V",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "muki_fork1:2", "type": "timeserie" },
    { "target": "muki_fork2:2", "type": "timeserie" }
   ]
  }
 ]
}