{
 "title": "NanoY Compressor",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "High/Low pressure, bar",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "nanoy_compr:0", "type": "timeserie" },
    { "target": "nanoy_compr:1", "type": "timeserie" }
   ]
  },
  {
   "title": "Water in/out temperature, C",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "nanoy_compr:2", "type": "timeserie" },
    { "target": "nanoy_compr:3", "type": "timeserie" }
   ]
  },
  {
   "title": "Gas/Oil temperature, C",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "nanoy_compr:4", "type": "timeserie" },
    { "target": "nanoy_compr:5", "type": "timeserie" }
   ]
  },
  {
   "title": "Motor Amps",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "nanoy_compr:7", "type": "timeserie" }
   ]
  }
 ]
}