{
 "title": "NanoY",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CH1: 60K plate",
   "type": "singlestat",
   "format": "kelvin",
   "valueName": "current",
   "targets": [
    { "target": "nanoy_CH1T" }
   ]
  },
  {
   "title": "CH2: 4K plate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "kelvin",
   "valueName": "current",
   "targets": [
    { "target": "nanoy_CH2T" }
   ]
  },
  {
   "title": "CH5: Still",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "kelvin",
   "valueName": "current",
   "targets": [
    { "target": "nanoy_CH5T" }
   ]
  },
  {
   "title": "CH6: Mixer",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "kelvin",
   "valueName": "current",
   "targets": [
    { "target": "nanoy_CH6T" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "none", "label": "temperature" }
   ],
   "targets": [
    { "target": "nanoy_CH1T", "type": "timeserie" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "nanoy_CH2T", "type": "timeserie" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "nanoy_CH5T", "type": "timeserie" }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "nanoy_CH6T", "type": "timeserie" }
   ]
  },
  {
   "title": "CH3:",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "nanoy_CH3T" },
    { "target": "nanoy_CH3R" }
   ]
  },
  {
   "title": "CH4:",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "nanoy_CH4T" },
    { "target": "nanoy_CH4R" }
   ]
  },
  {
   "title": "CH7:",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "nanoy_CH7T" },
    { "target": "nanoy_CH7R" }
   ]
  },
  {
   "title": "CH8:",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "short", "label": "temperature" }
   ],
   "targets": [
    { "target": "nanoy_CH8T" },
    { "target": "nanoy_CH8R" }
   ]
  },
  {
   "title": "flow",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "nanoy_flow" }
   ]
  },
  {
   "title": "P1: Vacuum can",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "nanoy_gauge:0" }
   ]
  },
  {
   "title": "P2: Still",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "target": "nanoy_gauge:1" }
   ]
  },
  {
   "title": "P3: Cond.line",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "nanoy_gauge:2" }
   ]
  },
  {
   "title": "P4: Scroll out",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "nanoy_gauge:3" }
   ]
  },
  {
   "title": "P5: Tanks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "nanoy_gauge:4" }
   ]
  },
  {
   "title": "P6: Service line",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 19 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "target": "nanoy_gauge:5" }
   ]
  },
  {
   "title": "flow",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "umol/s ?" }
   ],
   "targets": [
    { "target": "nanoy_flow" }
   ]
  },
  {
   "title": "P1: Vacuum can / P6: service line",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "nanoy_gauge:0" },
    { "target": "nanoy_gauge:5" }
   ]
  },
  {
   "title": "P2: Still / P3: Condensing line",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "nanoy_gauge:1" },
    { "target": "nanoy_gauge:2" }
   ]
  },
  {
   "title": "P4: Scroll out / P5: tanks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "nanoy_gauge:3" },
    { "target": "nanoy_gauge:4" }
   ]
  }
 ]
}