{
 "title": "Prototype",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1h",
 "panels": [
  {
   "title": "CH1 (50K)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "proto_CH1:1", "type": "timeserie" }
   ]
  },
  {
   "title": "CH3 (4K)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "proto_CH3:1", "type": "timeserie" }
   ]
  },
  {
   "title": "CH5",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "proto_CH5:1", "type": "timeserie" }
   ]
  },
  {
   "title": "CH7",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "proto_CH7:1", "type": "timeserie" },
    { "target": "proto_CH7:0", "type": "timeserie" }
   ]
  },
  {
   "title": "CH2",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "proto_CH2:1", "type": "timeserie" }
   ]
  },
  {
   "title": "CH4",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "proto_CH4:1", "type": "timeserie" }
   ]
  },
  {
   "title": "CH6 (Still)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "proto_CH6:1", "type": "timeserie" }
   ]
  },
  {
   "title": "CH8 (MXC)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "proto_CH8:1", "type": "timeserie" }
   ]
  }
 ]
}