{
 "title": "ROTA-bindat",
 "time": { "from": "2001-04-02T07:16:57.378Z", "to": "2001-04-02T15:04:28.514Z" },
 "panels": [
  {
   "title": "rotation, mrad/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "rota_bindat:0", "type": "timeserie" }
   ]
  },
  {
   "title": "A: set/measured current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "rota_bindat:1", "type": "timeserie" },
    { "target": "rota_bindat:2", "type": "timeserie" }
   ]
  },
  {
   "title": "B: set/measured current",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "rota_bindat:5", "type": "timeserie" },
    { "target": "rota_bindat:6", "type": "timeserie" }
   ]
  },
  {
   "title": "A: abs/disp",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "rota_bindat:3", "type": "timeserie" },
    { "target": "rota_bindat:4", "type": "timeserie" }
   ]
  },
  {
   "title": "B: abs/disp",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "rota_bindat:7", "type": "timeserie" },
    { "target": "rota_bindat:8", "type": "timeserie" }
   ]
  }
 ]
}