{
 "title": "Weather Tapiola",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "temperature, C",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "weather_tapiola_t", "type": "timeserie" }
   ]
  },
  {
   "title": "pressure at sea level, hPa",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "weather_tapiola_p_sea", "type": "timeserie" }
   ]
  },
  {
   "title": "relative humidity, %",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "weather_tapiola_humidity", "type": "timeserie" }
   ]
  },
  {
   "title": "snow depth, cm",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "weather_tapiola_snow_aws", "type": "timeserie" },
    { "target": "weather_lohja_snow_aws", "type": "timeserie" },
    { "target": "weather_lahti_snow_aws", "type": "timeserie" },
    { "target": "weather_tampere_snow_aws", "type": "timeserie" }
   ]
  }
 ]
}